# Simple workflow for deploying static content to GitHub Pages
name: Deploy website to pages

on:
  # Runs on pushes targeting the default branch
  push:
    branches: ["main"]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

# Allow only one concurrent deployment, skipping runs queued between the run in-progress and latest queued.
# However, do NOT cancel in-progress runs as we want to allow these production deployments to complete.
concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  # Single deploy job since we're just deploying
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
      - name: Use Node.JS
        uses: actions/setup-node@v3
        with:
          node-version: '23.x'
      - name: Configure GitHub Pages
        uses: actions/configure-pages@v3
      - run: npm install
      - run: npm run build
      - name: Upload Artifacts
        uses: actions/upload-pages-artifact@v1
        with:
          path: "./dist"
      - name: Deploy
        id: deployment
        uses: actions/deploy-pages@v1
